Update Alive.php
polyfony-inc/bundle-alive pull request #2
Opened 2019-12-02 13:37 UTC by WarenN

Pour ce qui est du Config.ini, je propose ceci en échange de "bridge_expected_date_column" et "bridge_expected_date_value" (moins restrictif)

[alive]
.../...
bridge_expected_column = "site_nom"
bridge_expected_column_value = "SIB TEST"

2019-12-02 13:52 UTC, AnnoyingTechnology commented
Sauf que l'idée c'est justement de tester la conversion d'une date, pour s'assurer que ça aussi est correct/fonctionne
mais si ça peut être testé autrement, OK

-

www.julienarnaud.fr
06 71 66 91 23

December 2, 2019 2:37 PM, "Philippe" <notifications@github.com (mailto:%22Philippe%22%20<notifications@github.com>)> wrote:
	Pour ce qui est du Config.ini, je propose ceci en échange de "bridge_expected_date_column" et "bridge_expected_date_value" (moins restrictif) 

	[alive]
.../...
bridge_expected_column = "site_nom"
bridge_expected_column_value = "SIB TEST" 
------------------------------------
You can view, comment on, or merge this pull request online at:
	https://github.com/polyfony-inc/bundle-alive/pull/2 (https://github.com/polyfony-inc/bundle-alive/pull/2) 

Commit Summary
	* Update Alive.php
File Changes
	*  M Alive/Controllers/Alive.php (https://github.com/polyfony-inc/bundle-alive/pull/2/files#diff-0) (42)
Patch Links:
	* https://github.com/polyfony-inc/bundle-alive/pull/2.patch (https://github.com/polyfony-inc/bundle-alive/pull/2.patch) 
	* https://github.com/polyfony-inc/bundle-alive/pull/2.diff (https://github.com/polyfony-inc/bundle-alive/pull/2.diff) 
	—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub (https://github.com/polyfony-inc/bundle-alive/pull/2?email_source=notifications&email_token=ABIW56FI5RSIFELZIUPGMIDQWUFP3A5CNFSM4JTV5NB2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4H5IOPWQ), or unsubscribe (https://github.com/notifications/unsubscribe-auth/ABIW56HYIP4KXKUC5ITDXY3QWUFP3ANCNFSM4JTV5NBQ).

2019-12-02 15:17 UTC, WarenN commented
oui, on peut le tester autre part.
En plus si l'on voulait tester la conversion des dates, il faudrait tester tous les formats disponibles dans FM

2019-12-02 17:03 UTC, AnnoyingTechnology requested changes

2019-12-02 17:03 UTC, AnnoyingTechnology commented on Alive/Controllers/Alive.php
> +		if( Config::get('alive', 'assert_bridge_status') !== null && Config::get('alive', 'assert_bridge_status') == 1 ) {
Il y a une vérif en trop car Config::get() effectue déjà des vérification sur la nullité 

```php
	
	public static function get(string $group, $key=null) {
		// return the proper config
		return($key ? 
			// make sure the group's key exists before trying to access it
			(isset(self::$_config['Current'][$group][$key]) ? self::$_config['Current'][$group][$key] : null) : 
			// make sure the group exists before trying to access it
			(isset(self::$_config['Current'][$group]) ? self::$_config['Current'][$group] : null)
		);
	}

```

2019-12-02 17:03 UTC, AnnoyingTechnology commented on Alive/Controllers/Alive.php
> +			$Request_query = new Query;
Mauvaise casse de la variable (ça devrait être du snake_case)

2019-12-02 17:03 UTC, AnnoyingTechnology commented on Alive/Controllers/Alive.php
> +			$Request_query->query(
factorisable
```php
$birdge_query = (new Query)
    ->query('...');

```

2019-12-02 17:03 UTC, AnnoyingTechnology commented on Alive/Controllers/Alive.php
> +			else {
devrait être un `elseif` (un niveau de [complexité conditionnelle](https://resources.infosecinstitute.com/conditional-complexity-of-risk-models/) gagné)

2019-12-03 08:52 UTC, AnnoyingTechnology approved these changes

2019-12-03 08:52 UTC, AnnoyingTechnology commented on Alive/Controllers/Alive.php
> +				Throw new Exception("The object of the Filemaker database has a wrong match value");
Pas très grammaticalement valide ça ;)
`The object's column value differs from what we were expecting`

2019-12-03 08:53 UTC, merged